name: hello-world
on: push
jobs:
  jeremy-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
        run: echo "I love you Jeremy"
      - name: finish-step
        run: echo "Let's finish nice shall we, Jeremy"
        run: echo "OK! Good Night"
    