name: Java CI
on: push
jobs:
  clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-and-build
        uses: actions/checkout@v2 
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: jeremy-artifact
          path: .
  build:
    needs: clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download repo
        uses: actions/download-artifact@v2
        with:
          name: jeremy-artifact
          path: .    
      - name: build-application
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: test
        run: ci/unit-test-app.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jeremy-artifact
          path: .
